package co.edu.uniquindio.proyectofinalhotelfx.Modelo.Enums;

public enum Ciudad {
    ARMENIA, MEDELLIN, CARTAGENA, BOGOTA, SANTAMARTA, SANANDRES, BARRANQUILLA, CALI,
    BUCARAMANGA, PEREIRA, MANIZALES, VILLALEYVA, BARICHARA, LETICIA, GUATAPE, VALLEDUPAR,
    POPAYAN, RIONEGRO, PASTO, CUCUTA, BUENAVENTURA
}
